# Generated by Django 3.1 on 2020-08-19 21:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 19, 59, 715039, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
