language: python
python:
  - "3.8"
install: "pip3 install -r requirements.txt"
before_script:
  - cp .env.example .env
  - python manage.py migrate
script:
  - python manage.py test --settings=parsifal.test_settings
sudo: false